# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conclusion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Conclusion_esc1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(742, 503)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 60, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(100, 130, 571, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_atras = QtWidgets.QPushButton(Dialog)
        self.pushButton_atras.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton_atras.setObjectName("pushButton_atras")
        self.pushButton_descargarReporte = QtWidgets.QPushButton(Dialog)
        self.pushButton_descargarReporte.setGeometry(QtCore.QRect(330, 380, 111, 31))
        self.pushButton_descargarReporte.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton_descargarReporte.setObjectName("pushButton_descargarReporte")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Conclusion"))
        self.label.setText(_translate("Dialog", "Conclusion de la evaluación"))
        self.pushButton_atras.setText(_translate("Dialog", "Atras"))
        self.pushButton_descargarReporte.setText(_translate("Dialog", "Descargar Reporte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Conclusion_esc1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
