# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaesc1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaEsc1(object):
    def setupUi(self, ventanaEsc1):
        ventanaEsc1.setObjectName("ventanaEsc1")
        ventanaEsc1.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ventanaEsc1)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(410, 90, 361, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 50, 321, 191))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 51, 16))
        self.label_2.setObjectName("label_2")
        self.media_flujo = QtWidgets.QLineEdit(self.groupBox)
        self.media_flujo.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.media_flujo.setObjectName("media_flujo")
        self.desviacionE_flujo = QtWidgets.QLineEdit(self.groupBox)
        self.desviacionE_flujo.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.desviacionE_flujo.setObjectName("desviacionE_flujo")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 260, 321, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 51, 16))
        self.label_4.setObjectName("label_4")
        self.media_inv = QtWidgets.QLineEdit(self.groupBox_2)
        self.media_inv.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.media_inv.setObjectName("media_inv")
        self.desviacionE_inv = QtWidgets.QLineEdit(self.groupBox_2)
        self.desviacionE_inv.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.desviacionE_inv.setObjectName("desviacionE_inv")
        self.boton_home = QtWidgets.QPushButton(self.centralwidget)
        self.boton_home.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.boton_home.setObjectName("boton_home")
        self.boton_simular = QtWidgets.QPushButton(self.centralwidget)
        self.boton_simular.setGeometry(QtCore.QRect(510, 460, 75, 23))
        self.boton_simular.setObjectName("boton_simular")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 460, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 10, 71, 16))
        self.label_5.setObjectName("label_5")
        ventanaEsc1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ventanaEsc1)
        self.statusbar.setObjectName("statusbar")
        ventanaEsc1.setStatusBar(self.statusbar)

        self.retranslateUi(ventanaEsc1)
        QtCore.QMetaObject.connectSlotsByName(ventanaEsc1)

    def retranslateUi(self, ventanaEsc1):
        _translate = QtCore.QCoreApplication.translate
        ventanaEsc1.setWindowTitle(_translate("ventanaEsc1", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ventanaEsc1", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ventanaEsc1", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ventanaEsc1", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ventanaEsc1", "Page"))
        self.groupBox.setTitle(_translate("ventanaEsc1", "Flujo"))
        self.label.setText(_translate("ventanaEsc1", "Media"))
        self.label_2.setText(_translate("ventanaEsc1", "D. Estandar"))
        self.groupBox_2.setTitle(_translate("ventanaEsc1", "Inversion Inicial"))
        self.label_3.setText(_translate("ventanaEsc1", "Media"))
        self.label_4.setText(_translate("ventanaEsc1", "D. Estandar"))
        self.boton_home.setText(_translate("ventanaEsc1", "HOME"))
        self.boton_simular.setText(_translate("ventanaEsc1", "SIMULAR"))
        self.pushButton_3.setText(_translate("ventanaEsc1", "CONCLUSION"))
        self.label_5.setText(_translate("ventanaEsc1", "ESCENARIO 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaEsc1 = QtWidgets.QMainWindow()
    ui = Ui_ventanaEsc1()
    ui.setupUi(ventanaEsc1)
    ventanaEsc1.show()
    sys.exit(app.exec_())
